restartPolicy: OnFailure

concurrencyPolicy: Forbid
   
#At 00:00 on Sunday
schedule: "@weekly"
backoffLimit: 2

username: "use --set username=xxx"
password: "use --set password=xxx"

# The id inside of MediSpan.xml that you want to update.
dataAccessId: "PostgresData"
   
installs:
  # SPECIFY_DIRECTORY | DOWNLOAD_AND_INSTALL | DELETE
  type: DOWNLOAD_AND_INSTALL
  specifyDirectory:
    # Can be either "FULL_DB" or "INCREMENTAL_DB"
    type: INCREMENTAL_DB
  downloadAndInstall:
    # encyrpted password <WebDownload_Password> inside of MediSpan.xml
    password: "somebase64string"
  

image:
  repository: caffeine01/medispan-installer
  #Overrides all the jdbc drivers to use a newer version of postgres
  tag: "jdbc-postgres-202502071531"
  #Uses the all built in jdbc drivers
  # tag: "jdbc-default"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

conf:
  # Use a real MediSpan.xml file.
  MediSpan.xml: |
    <!-- Very imcomplete MediSpan.xml -->
    <?xml version="1.0" encoding="utf-8" ?>
    <MediSpanConfig>
      <DataAccess>
      </DataAccess>
    </MediSpanConfig>

  #Override a specific saved installer configuration file if you want
  #Use M6N_AUTO_START to specify the Autostart InstallerId
  # MediSpan.Install.User.Config.xml: |
  #   <?xml version="1.0" encoding="UTF-8" standalone="no"?>
  #   <MediSpanConfig>
  #       <Install>
  #           <Installs>
  #               <SPECIFY_DIRECTORY>
  #                   <Installer>Directory</Installer>
  #                   <Directory_Path>/custom-data-folder</Directory_Path>
  #                   <Product_DataAccessId>OracleData</Product_DataAccessId>
  #               </SPECIFY_DIRECTORY>
  #               <DOWNLOAD_AND_INSTALL>
  #                   <Installer>MBL.Web</Installer>
  #                   <Directory_Path>/var/medispan/data</Directory_Path>
  #                   <Product_DataAccessId>OracleData</Product_DataAccessId>
  #                   <WebDownload_UserId>medispanusername</WebDownload_UserId>
  #                   <WebDownload_Password>Ww4iu50s==</WebDownload_Password>
  #               </DOWNLOAD_AND_INSTALL>
  #           </Installs>
  #       </Install>
  #   </MediSpanConfig>

extraEnvs:
  # - name: M6N_AUTO_START
  #   value: "/Autostart:DOWNLOAD_AND_INSTALL"

extraVolumes: []

extraVolumeMounts: []
