apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "m6n-installer.labels" . | nindent 4 }}
  name: {{ include "m6n-installer.fullname" . }}
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          volumes:
          - name: conf
            configMap:
              name: {{ include "m6n-installer.fullname" . }}-conf
              defaultMode: 420
          containers:
          - name: {{ .Chart.Name }}
            {{- with .Values.image }}
            image: "{{ .repository }}:{{ .tag }}"
            imagePullPolicy: {{ .pullPolicy }}
           {{- end }}
            envFrom:
            - secretRef:
                name: {{ include "m6n-installer.fullname" . }}
            volumeMounts:
            - mountPath: /medispan/conf
              name: conf
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}