services:
  m6n-downloader:
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
      - ghcr.io/bluestep-systems/m6n-downloader:latest
    image: ghcr.io/bluestep-systems/m6n-downloader


