apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "m6n-installer.labels" . | nindent 4 }}
  name: {{ include "m6n-installer.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          volumes:
          - name: conf
            configMap:
              name: {{ include "m6n-installer.fullname" . }}-conf
              defaultMode: 420
          {{- toYaml .Values.extraVolumes | nindent 10 }}
          containers:
          - name: {{ .Chart.Name }}
            {{- with .Values.image }}
            image: "{{ .repository }}:{{ .tag }}"
            imagePullPolicy: {{ .pullPolicy }}
            {{- end }}
            env:
            - name: M6N_DATA_ACCESS_ID
              value: "{{ .Values.dataAccessId }}"
            - name: M6N_INSTALLS_TYPE
              value: "{{ .Values.installs.type }}"
            - name: M6N_INSTALLS_SPECIFY_DIRECTORY_TYPE
              value: "{{ .Values.installs.specifyDirectory.type }}"
              {{- if .Values.extraEnvs }}
                {{- toYaml .Values.extraEnvs | nindent 12 }}
              {{- end }}
            envFrom:
            - secretRef:
                name: {{ include "m6n-installer.fullname" . }}
            volumeMounts:
            - mountPath: /etc/medispan/conf
              name: conf
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}