/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.bluestep.medispan.updater;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        final App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
