FROM ghcr.io/bluestep-systems/medispan-automation:jdbc-default

ARG PGVERSION
RUN echo "PGVERSION=${PGVERSION}"
# Medispan's included postgres drivers are old and do not work with the latest authentication scram-sha-256
RUN mkdir -p /etc/medispan/drivers && \
  curl --fail -L https://jdbc.postgresql.org/download/postgresql-${PGVERSION}.jar -o /etc/medispan/drivers/postgresql-${PGVERSION}.jar

